"""empty message

Revision ID: 2eeab8febd00
Revises: ca047bc28e36
Create Date: 2024-10-19 22:30:57.064034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eeab8febd00'
down_revision = 'ca047bc28e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('published_year',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('published_year',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
