"""empty message

Revision ID: 6a55b50d6ea3
Revises: 2eeab8febd00
Create Date: 2024-10-19 22:35:04.730655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a55b50d6ea3'
down_revision = '2eeab8febd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('published_year',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('published_year',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
